export const leveles = [
    [{ firstOperand: 4, operation: "+ 3", }, // 1 level
    { firstOperand: 7, operation: "+ 3", },
    { firstOperand: 10, operation: "- 6" },
    { firstOperand: 4, operation: "+ 5" },
    { firstOperand: 9, operation: "- 3" },
    { firstOperand: 6, operation: "- 4" },
    { firstOperand: 2, operation: "+ 6" },
    { firstOperand: 8, operation: "+ 2" },
    { firstOperand: 10, operation: "- 5" },
    { firstOperand: 5, operation: "+ 1" },
    { firstOperand: 6, operation: "+ 2" },
    { firstOperand: 8, }],
    [{ firstOperand: 7, operation: "+ 2", }, // 2 level
    { firstOperand: 9, operation: "+ 1", },
    { firstOperand: 10, operation: "- 7" },
    { firstOperand: 3, operation: "+ 5" },
    { firstOperand: 8, operation: "- 3" },
    { firstOperand: 5, operation: "- 4" },
    { firstOperand: 1, operation: "+ 7" },
    { firstOperand: 8, operation: "- 2" },
    { firstOperand: 6, operation: "+ 3" },
    { firstOperand: 9, operation: "+ 1" },
    { firstOperand: 10, operation: "- 7" },
    { firstOperand: 3, }],
    [{ firstOperand: 10, operation: "- 8", }, // 3 level
    { firstOperand: 2, operation: "- 2", },
    { firstOperand: 0, operation: "+ 9" },
    { firstOperand: 9, operation: "- 5" },
    { firstOperand: 4, operation: "+ 4" },
    { firstOperand: 8, operation: "+ 2" },
    { firstOperand: 10, operation: "- 9" },
    { firstOperand: 1, operation: "+ 7" },
    { firstOperand: 8, operation: "- 5" },
    { firstOperand: 3, operation: "+ 7" },
    { firstOperand: 10, operation: "- 4" },
    { firstOperand: 6, }],
    [{ firstOperand: 10, operation: "+ 9", }, //4 level
    { firstOperand: 19, operation: "- 7", },
    { firstOperand: 12, operation: "- 5" },
    { firstOperand: 7, operation: "+ 8" },
    { firstOperand: 15, operation: "+ 5" },
    { firstOperand: 20, operation: "- 11" },
    { firstOperand: 9, operation: "+ 2" },
    { firstOperand: 11, operation: "+ 7" },
    { firstOperand: 18, operation: "- 10" },
    { firstOperand: 8, operation: "+ 6" },
    { firstOperand: 14, operation: "- 7" },
    { firstOperand: 7, }],
    [{ firstOperand: 12, operation: "- 5", }, //5 level
    { firstOperand: 7, operation: "+ 9", },
    { firstOperand: 16, operation: "+ 3" },
    { firstOperand: 19, operation: "- 4" },
    { firstOperand: 15, operation: "- 9" },
    { firstOperand: 6, operation: "+ 7" },
    { firstOperand: 13, operation: "+ 4" },
    { firstOperand: 17, operation: "- 9" },
    { firstOperand: 8, operation: "+ 5" },
    { firstOperand: 13, operation: "+ 7" },
    { firstOperand: 20, operation: "- 12" },
    { firstOperand: 8, }],
    [{ firstOperand: 20, operation: "- 12", }, // 6 level
    { firstOperand: 8, operation: "+ 8", },
    { firstOperand: 16, operation: "- 13" },
    { firstOperand: 3, operation: "+ 9" },
    { firstOperand: 12, operation: "+ 7" },
    { firstOperand: 19, operation: "- 15" },
    { firstOperand: 4, operation: "+ 7" },
    { firstOperand: 11, operation: "- 5" },
    { firstOperand: 6, operation: "+ 14" },
    { firstOperand: 20, operation: "- 13" },
    { firstOperand: 7, operation: "+ 5" },
    { firstOperand: 12, }],
    [{ firstOperand: 49, operation: "- 7", }, // 7 level
    { firstOperand: 42, operation: ": 7", },
    { firstOperand: 6, operation: "x 10" },
    { firstOperand: 60, operation: "+ 21" },
    { firstOperand: 81, operation: "+ 19" },
    { firstOperand: 100, operation: "- 51" },
    { firstOperand: 49, operation: ": 7" },
    { firstOperand: 7, operation: "x 8" },
    { firstOperand: 56, operation: "- 20" },
    { firstOperand: 36, operation: ": 9" },
    { firstOperand: 4, operation: "x 7" },
    { firstOperand: 28, }],
    [{ firstOperand: 56, operation: ": 8", }, // 8 level
    { firstOperand: 7, operation: "+ 18", },
    { firstOperand: 25, operation: "+ 11" },
    { firstOperand: 36, operation: ": 6" },
    { firstOperand: 6, operation: "x 9" },
    { firstOperand: 54, operation: "- 9" },
    { firstOperand: 45, operation: "+ 36" },
    { firstOperand: 81, operation: ": 9" },
    { firstOperand: 9, operation: "x 3" },
    { firstOperand: 27, operation: "- 13" },
    { firstOperand: 14, operation: "- 6" },
    { firstOperand: 8, }],
    [{ firstOperand: 24, operation: ": 8", }, // 9 level
    { firstOperand: 3, operation: "x 6", },
    { firstOperand: 18, operation: "+ 7" },
    { firstOperand: 25, operation: "+ 24" },
    { firstOperand: 49, operation: ": 7" },
    { firstOperand: 7, operation: "x 4" },
    { firstOperand: 28, operation: "- 15" },
    { firstOperand: 13, operation: "+ 59" },
    { firstOperand: 72, operation: ": 9" },
    { firstOperand: 8, operation: "x 5" },
    { firstOperand: 40, operation: "- 11" },
    { firstOperand: 29, }],
    [{ firstOperand: 90, operation: "+ 10", }, // 10 level
    { firstOperand: 100, operation: "- 36", },
    { firstOperand: 64, operation: "- 16" },
    { firstOperand: 48, operation: ": 6" },
    { firstOperand: 8, operation: ": 4" },
    { firstOperand: 2, operation: "x 10" },
    { firstOperand: 20, operation: "+ 15" },
    { firstOperand: 35, operation: ": 7" },
    { firstOperand: 5, operation: "+ 40" },
    { firstOperand: 45, operation: ": 5" },
    { firstOperand: 9, operation: "+ 34" },
    { firstOperand: 43, }],
    [{ firstOperand: 4, operation: "x 8", }, // 11 level
    { firstOperand: 32, operation: "- 7", },
    { firstOperand: 25, operation: "- 9" },
    { firstOperand: 16, operation: ": 2" },
    { firstOperand: 8, operation: "+ 56" },
    { firstOperand: 64, operation: ": 8" },
    { firstOperand: 8, operation: "+ 59" },
    { firstOperand: 67, operation: "- 4" },
    { firstOperand: 63, operation: ": 7" },
    { firstOperand: 9, operation: "x 4" },
    { firstOperand: 36, operation: "+ 57" },
    { firstOperand: 93, }],
    [{ firstOperand: 21, operation: ": 3", }, // 12 level
    { firstOperand: 7, operation: "x 5", },
    { firstOperand: 35, operation: "+ 9" },
    { firstOperand: 44, operation: "- 20" },
    { firstOperand: 24, operation: ": 6" },
    { firstOperand: 4, operation: "x 3" },
    { firstOperand: 12, operation: "+ 18" },
    { firstOperand: 30, operation: ": 5" },
    { firstOperand: 6, operation: "x 1" },
    { firstOperand: 6, operation: "x 9" },
    { firstOperand: 54, operation: "- 17" },
    { firstOperand: 37, }],
    [{ firstOperand: 22, operation: "- 7", }, // 13 level
    { firstOperand: 15, operation: "x 3", },
    { firstOperand: 45, operation: "+ 3" },
    { firstOperand: 48, operation: ": 2" },
    { firstOperand: 24, operation: "- 8" },
    { firstOperand: 16, operation: "x 5" },
    { firstOperand: 80, operation: "- 29" },
    { firstOperand: 51, operation: ": 3" },
    { firstOperand: 17, operation: "x 2" },
    { firstOperand: 34, operation: "x 2" },
    { firstOperand: 68, operation: "- 29" },
    { firstOperand: 39, }],
    [{ firstOperand: 44, operation: ": 4", }, // 14 level
    { firstOperand: 11, operation: "x 9", },
    { firstOperand: 99, operation: "- 63" },
    { firstOperand: 36, operation: ": 3" },
    { firstOperand: 12, operation: "x 5" },
    { firstOperand: 60, operation: ": 4" },
    { firstOperand: 15, operation: "+ 39" },
    { firstOperand: 54, operation: ": 3" },
    { firstOperand: 18, operation: "x 4" },
    { firstOperand: 72, operation: "- 22" },
    { firstOperand: 50, operation: "- 29" },
    { firstOperand: 21, }],
    [{ firstOperand: 76, operation: ": 4", }, // 15 level
    { firstOperand: 19, operation: "x 3", },
    { firstOperand: 57, operation: "+ 38" },
    { firstOperand: 95, operation: ": 5" },
    { firstOperand: 19, operation: "+ 27" },
    { firstOperand: 46, operation: "+ 18" },
    { firstOperand: 64, operation: ": 4" },
    { firstOperand: 16, operation: "x 6" },
    { firstOperand: 96, operation: "- 41" },
    { firstOperand: 55, operation: "- 27" },
    { firstOperand: 28, operation: ": 2" },
    { firstOperand: 14, }],
    [{ firstOperand: 45, operation: ": 15", }, // 16 level
    { firstOperand: 3, operation: "x 17", },
    { firstOperand: 51, operation: "+ 38" },
    { firstOperand: 89, operation: "- 14" },
    { firstOperand: 75, operation: ": 15" },
    { firstOperand: 5, operation: "x 13" },
    { firstOperand: 65, operation: "- 49" },
    { firstOperand: 16, operation: "x 3" },
    { firstOperand: 48, operation: ": 24" },
    { firstOperand: 2, operation: "x 17" },
    { firstOperand: 34, operation: "- 15" },
    { firstOperand: 19, }],
    [{ firstOperand: 36, operation: ": 18", }, // 17 level
    { firstOperand: 2, operation: "x 27", },
    { firstOperand: 54, operation: "- 29" },
    { firstOperand: 25, operation: "x 4" },
    { firstOperand: 100, operation: ": 5" },
    { firstOperand: 20, operation: "+ 44" },
    { firstOperand: 64, operation: ": 16" },
    { firstOperand: 4, operation: "x 23" },
    { firstOperand: 92, operation: ": 46" },
    { firstOperand: 2, operation: "x 19" },
    { firstOperand: 38, operation: "+ 55" },
    { firstOperand: 93, }],
    [{ firstOperand: 78, operation: ": 26", }, // 18 level
    { firstOperand: 3, operation: "x 35", },
    { firstOperand: 105, operation: "+ 20" },
    { firstOperand: 125, operation: ": 25" },
    { firstOperand: 5, operation: "x 23" },
    { firstOperand: 115, operation: "+ 36" },
    { firstOperand: 151, operation: "- 32" },
    { firstOperand: 119, operation: ": 17" },
    { firstOperand: 7, operation: "x 15" },
    { firstOperand: 105, operation: "x 2" },
    { firstOperand: 210, operation: ": 70" },
    { firstOperand: 3, }],

]