export const leveles = [
    [{ firstOperand: 0, operation: "+ 2", },
    { firstOperand: 2, operation: "+ 1", },
    { firstOperand: 3, operation: "+ 1" },
    { firstOperand: 4, operation: "+ 2" },
    { firstOperand: 6, operation: "- 1" },
    { firstOperand: 5, operation: "- 1" },
    { firstOperand: 4, operation: "+ 2" },
    { firstOperand: 6, operation: "+ 2" },
    { firstOperand: 8, operation: "- 1" },
    { firstOperand: 7, operation: "+ 2" },
    { firstOperand: 9, operation: "- 1" },
    { firstOperand: 8, }],
    [{ firstOperand: 49, operation: "- 7", },
    { firstOperand: 42, operation: ": 7", },
    { firstOperand: 6, operation: "x 10" },
    { firstOperand: 60, operation: "+ 21" },
    { firstOperand: 81, operation: "+ 19" },
    { firstOperand: 100, operation: "- 51" },
    { firstOperand: 49, operation: ": 7" },
    { firstOperand: 7, operation: "x 8" },
    { firstOperand: 56, operation: "- 20" },
    { firstOperand: 36, operation: ": 9" },
    { firstOperand: 4, operation: "x 7" },
    { firstOperand: 28, }],

]